Global:
  use_gpu: true
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 2
  save_model_dir: /chunchet/CCPD2019/fine_tuned_ccpd/east
  save_epoch_step: 50
  eval_batch_step:
  - 0
  - 20
  cal_metric_during_train: false
  pretrained_model: /chunchet/CCPD2019/ppocr_east/det_mv3_east_v2.0_train/best_accuracy
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: null
  save_res_path: null
Architecture:
  model_type: det
  algorithm: EAST
  Transform: null
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    name: EASTFPN
    model_name: small
  Head:
    name: EASTHead
    model_name: small
Loss:
  name: EASTLoss
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 5.0e-05
  regularizer:
    name: L2
    factor: 0
PostProcess:
  name: EASTPostProcess
  score_thresh: 0.8
  cover_thresh: 0.1
  nms_thresh: 0.2
Metric:
  name: DetMetric
  main_indicator: hmean
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /chunchet/CCPD2019/train
    label_file_list:
    - /chunchet/CCPD2019/train.txt
    ratio_list:
    - 1.0
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - EASTProcessTrain:
        image_shape:
        - 512
        - 512
        background_ratio: 0.125
        min_crop_side_ratio: 0.1
        min_text_size: 10
    - KeepKeys:
        keep_keys:
        - image
        - score_map
        - geo_map
        - training_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 4
    num_workers: 8
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /chunchet/CCPD2019/val
    label_file_list:
    - /chunchet/CCPD2019/val.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - DetResizeForTest:
        limit_side_len: 2400
        limit_type: max
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - ignore_tags
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 4
    num_workers: 2
profiler_options: null
